name: Temp
on: [ push, pull_request ]
jobs:
  temp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Install modules
        run: yarn
      - name: Run gui temp
        run: yarn cypress:temp
